apiVersion: apps/v1
kind: Deployment
metadata:
  name: curadoria-agil
spec:
  replicas: 2
  selector:
    matchLabels:
      app: curadoria-agil
  template:
    metadata:
      labels:
        app: curadoria-agil
    spec:
      containers:
      - name: curadoria-agil
        image: curadoria-agil:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
